### ISSUE TITLE
Navbar covers content in Chrome

### ISSUE THREAD

**Issue by haakon-soegnen** [FNLF/fnlf-client#126]

**Comment by einarhuseby** [comment]
Same as #54 ?

**Comment by haakon-soegnen** [comment]
No, this seems to be caused by navbar-branding taking too much vertical space

**Comment by einarhuseby** [comment]
I'm getting the same result as #54 and when when in xs screen size without the application switcher it behaves as expected

![observations009](https://cloud.githubusercontent.com/assets/1221923/6564974/01e39706-c6ad-11e4-916c-251963d4d0f9.png)

![observations010](https://cloud.githubusercontent.com/assets/1221923/6564975/021b7acc-c6ad-11e4-8908-8a4b25b2b899.png)

**Comment by einarhuseby** [comment]
Actually chrome needs the ul navbar elements to be wrapped in an element; span seems to fix this
