### ISSUE TITLE
Open registered observation cases doesn't work - iphone safari

### ISSUE THREAD

**Issue by yhaugom** [FNLF/fnlf-client#144]
Sometimes when trying to open an observation case, nothing happens. Load bar appears for a brief moment (1 second), and disappears again. Nothing else happens, not even when trying again to open all my cases and others cases.

This works fine in safari in Yosemite OS X 10.10.2 though.

Sometimes I can access a case, sometimes I can't, but can't find the connection, reason or workaround.

**Comment by einarhuseby** [comment]
Seems to be quite a few unknowns with safari on osx and angular
