### ISSUE TITLE
Not possible to choose or set involved person in chain of events

### ISSUE THREAD

**Issue by yhaugom** [FNLF/fnlf-client#146]
In the textbox for involved persons, under chain of events ("Forløp"/"Hendinger i forløpet"), it is not possible to choose from added involved persons, or fill new value. 

Guess it should be possible to select one or more people from the involved persons list.

**Comment by einarhuseby** [comment]
Two non-members will give a duplicate error (both have id 0)

**Comment by haakon-soegnen** [comment]
Non members should get a unique id. Array length * -1 should work
