### ISSUE TITLE
Location should update if club is changed.

### ISSUE THREAD

**Issue by yhaugom** [FNLF/fnlf-client#147]
If a observation is registered on wrong club, it would be nice if, when correcting/changing the club, the location automatically would update, or at least be possible to change that dropzone home location from drop-down.

This may be related to other location bugs maybe?

**Comment by haakon-soegnen** [comment]
In some cases (Bømoen) the location should not update when swithing between VossFsk and BergenFsk

**Comment by haakon-soegnen** [comment]
Wontfix. Club should never change
