### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#189]
- Not possible to change club = no need to repopulate location list

New location:
- can drag marker to different coordinates but keep place name from service (adjust to real coordinates see "Bømoen" as example)
- Remove ariport selector and use closest from geojson automatically (frontend or backend geo query)
- If no airport or airport has no metar/taf, do not try to get metar/taf
- Always do yr lookup on creation of observation

Existing location:
- From observation select place by nickname in select list, but can drag map marker to change coordinates - fine tune (happened on student landing area, but still at nickname location (distinct))

Replaaces all other location issues

**Comment by haakon-soegnen** [comment]
https://github.com/allenhwkim/angularjs-google-maps
