### ISSUE TITLE
Config system supporting dev/prod versions

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#238]
We have had the GlobalService available in auth.
See this as a reference http://limitless-lowlands-6996.herokuapp.com/http://www.ng-newsletter.com/advent2013/%3F_escaped_fragment_=/day/5?_escaped_fragment_=/day/5#!/day/5

**Comment by einarhuseby** [comment]
See #307 and fnlf/fnlf-backend#81

**Comment by hakon-sognen** [comment]
Fixed in #307 with grunt instead of loading from backend
