### ISSUE TITLE
Adding data after case is rejected - error 404 on save

### ISSUE THREAD

**Issue by yhaugom** [FNLF/fnlf-client#318]
Entering weather info, gear data, number of jumps etc. Hit save and nothing is saved. 
{"_error":{"code":404,"message":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."},"_status":"ERR"}

The case has gone trough these steps;
1. case created by "HL"
2. Commented and edited by "HI"
3. Rejected with comment from "Fagsjef"
4. Rejected by "HI"
5. Tried editing and adding info (weather, gear, jumps etc)
6. Save doesn't work => error

Tried this first on iPhone 6 plus in safari, then iMac in Safari (ver 9.0.1) and Google Chrome (46.0.2490.86 (64-bit)). Same result in all the above.

Case # 274 "Hard landing" in live system.

(---Norsk orginaltekst---
Ting jeg skriver inn i Safari på feks iphone blir ikke lagret. Skreiv inn værdata, utstyrstype, erfaring, osv. Trykker lagre og alt er borte. Dette er i live-versjonen og ikke beta. 

Etter å ha prøvd nå på Mac og Safari fikk jeg samme resultat. Mulig dette er pga sakens status også.

Fikk feilmelding: {"_error":{"code":404,"message":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."},"_status":"ERR"}

Det gjelder f.eks sak #274 Hard landing.

Sakens forløp har til nå vært;
1. opprettet av HL
2. kommentert og redigert på av HI
3. avvist av Fagsjef
4. avvist av HI
5. forsøker å fylle inn mer info og lagre
6. Info blir ikke lagret.

Fungerer heller ikke nå i chrome, så da antar jeg det er pga sakens "status" kanskje?)

**Comment by haakon-soegnen** [comment]
Dette har blitt løst i versjonen som kjører på fnlfbeta.nlf.no. Det skal ikkje lenger vere mulig å redigere observasjonen uten at ein samtidig har rettighet til å lagre. Prøvde nettopp med https://fnlfbeta.nlf.no/app/obs/#!/observation/156

**Comment by yhaugom** [comment]
Hvordan løser vi det med saken jeg har liggende? Kan jeg få rettigheter til å endre igjen, eller må dere legge til info som mangler?

Mvh Yngve




On Sat, Dec 5, 2015 at 2:16 PM -0800, "haakon-soegnen" <notifications@github.com> wrote:





Dette har blitt løst i versjonen som kjører på fnlfbeta.nlf.no. Det skal ikkje lenger vere mulig å redigere observasjonen uten at ein samtidig har rettighet til å lagre. Prøvde nettopp med https://fnlfbeta.nlf.no/app/obs/#!/observation/156

---

**Comment by haakon-soegnen** [comment]
Har "HL" mulighet til å redigere? Evt sende inn til HI igjen?

**Comment by yhaugom** [comment]
Ja det hadde han visst. 

Y

 

Fra: haakon-soegnen [mailto:notifications@github.com] 
Sendt: 5. desember 2015 23:25
Til: FNLF/fnlf-client <fnlf-client@noreply.github.com>
Kopi: Yngve Haugom <yngve_haugom@hotmail.com>
Emne: Re: [fnlf-client] Adding data after case is rejected - error 404 on save (#318)

 

Har "HL" mulighet til å redigere? Evt sende inn til HI igjen?

**Comment by haakon-soegnen** [comment]
Så da har det ordna seg?

2015-12-07 8:35 GMT+01:00 Yngve Haugom <notifications@github.com>:

**Comment by yhaugom** [comment]
Ja, har fått sendt den videre nå.

 

Fra: haakon-soegnen [mailto:notifications@github.com] 
Sendt: 7. desember 2015 15:01
Til: FNLF/fnlf-client <fnlf-client@noreply.github.com>
Kopi: Yngve Haugom <yngve_haugom@hotmail.com>
Emne: Re: [fnlf-client] Adding data after case is rejected - error 404 on save (#318)

 

Så da har det ordna seg?

2015-12-07 8:35 GMT+01:00 Yngve Haugom <notifications@github.com <mailto:notifications@github.com> >:

**Comment by haakon-soegnen** [comment]
#299
