### ISSUE TITLE
Inline help

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#34]
Via tooltip/popover/aside - explain what elements are

**Comment by einarhuseby** [comment]
See also #33

**Comment by einarhuseby** [comment]
Need to have text saying that one should not use names in freetext fields since it will not be anonymized (by default). Should use "hopper 1", "hopper 2" etc

**Comment by haakon-soegnen** [comment]
Related to #218

**Comment by hakon-sognen** [comment]
- smaller icon
- smaller thinner text
- investigate popover/fullwidth-something on desktop
