### ISSUE TITLE
Forløpseditoren skremmer vannet av folk 

### ISSUE THREAD

**Issue by haakon-soegnen** [FNLF/fnlf-client#354]
Så er det denne forløpseditoren da. Skremmer visst vannet av mange og jeg er såpass biased at jeg tror det mer skyldes at man ikke skjønner hensikten men når jeg ser på min egen bruk så tror jeg å faktisk gjøre det til en totrinns løsning der man først bare legger inn tittler oppover på årsaker deretter nedover på konsekvenser og får en liste med titler man kan reorganisere. Og en knapp eller noe som tar man inn i forløpseditoren slik den er i dag hvor man kan fylle ut resten - når, hvem, hva, hvor, hvorledes - så fjerner vi hfk der

**Comment by hakon-sognen** [comment]
a1b5ed61af049f4852dfb01a99861fcf9d201918
