### ISSUE TITLE
Persondetails equipment

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#37]
Should this get data from backend? Typeahead?

**Comment by haakon-soegnen** [comment]
We could use the tagging service as the backend for this. Either with typeahead as in the tagging directive, or as a new select widget.

Then we could use the new tag manager to manage gear/manufacturers.

**Comment by haakon-soegnen** [comment]
Using new tagtypeahead directive with tagging service as backend for equipment types
