### ISSUE TITLE
Remove fullname from all parts of observation

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#56]
Names shall not be stored in database, use userresolver and membership number to display names

**Comment by einarhuseby** [comment]
Example:
<resolveuser userid="person.id"></resolveuser>

Where person.id is membership number.
This do not work with non members see #36

**Comment by einarhuseby** [comment]
Usage example '<resolveuser userid="observation.reporter">{{observation.reporter}}</resolveuser>'

**Comment by haakon-soegnen** [comment]
Need to do something clever with the ResolveService to show the resolved name inside the person selector
