### ISSUE TITLE
After workflow transition observation do not detect changes

### ISSUE THREAD

**Issue by einarhuseby** [FNLF/fnlf-client#93]
To repeat:
- make a workflow transition
- wait until observation reloads
- make change(s) to observation
=> no changes are detected, save btn and label are disabled

**Comment by einarhuseby** [comment]
Worfkflow.js calls $rootScope.loadObservation before closing the aside
loadObservation does not reset the observation hence retrives images again etc

**Comment by einarhuseby** [comment]
Resetting observation like `$scope.observation = {};` seems to do the trick, but... @haakon-soegnen got any comments?

**Comment by haakon-soegnen** [comment]
What about reloading the page after transitioning?

**Comment by einarhuseby** [comment]
Resetting observation works!
